#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Проверяем, есть ли флаг --no-verify
if [ "$HUSKY_GIT_PARAMS" = "--no-verify" ]; then
  echo "✅ Хук пропущен (использован --no-verify)"
  exit 0
fi

# Получаем текущее сообщение коммита
if [ -f ".git/COMMIT_EDITMSG" ]; then
  COMMIT_MSG=$(cat .git/COMMIT_EDITMSG)
  echo "📎 Текущее сообщение коммита: $COMMIT_MSG"
else
  COMMIT_MSG="feat: unknown commit message"
  echo "⚠️ Не удалось найти .git/COMMIT_EDITMSG"
fi

# Получаем текущую ветку
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

# Проверяем, начинается ли ветка с "feature/"
if echo "$CURRENT_BRANCH" | grep -q '^feature/'; then
  echo "🔄 Выполняем логику changeset для ветки $CURRENT_BRANCH"
  
  # Получаем путь к последнему файлу changeset
  CHANGESET_DIR=$(pwd)/.changeset
  CHANGESET_FILE=$(find "$CHANGESET_DIR" -type f -name "*.md" -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d' ')

  # Проверяем, существует ли файл и не пустой ли он
  if [ -f "$CHANGESET_FILE" ]; then
    if [ -s "$CHANGESET_FILE" ]; then
      echo "📄 changeset-файл найден и не пустой — изменения не вносятся"
      exit 0
    else
      echo "📄 changeset-файл найден, но пустой — продолжаем обработку"
    fi
  else
    echo "📄 changeset-файл не найден — ошибка"
    exit 0
  fi

  FILE_LINES=$(wc -l < "$CHANGESET_FILE" 2>/dev/null || echo 0)
  while [ "$FILE_LINES" -lt 5 ]; do
    echo "" >> "$CHANGESET_FILE"
    FILE_LINES=$((FILE_LINES + 1))
  done 

  commit_type="${COMMIT_MSG%%:*}"
  commit_description="${COMMIT_MSG#*: }" 

  awk 'NR == 1 { print "---\n" } { print }' "$CHANGESET_FILE" > "$CHANGESET_FILE.tmp" && mv "$CHANGESET_FILE.tmp" "$CHANGESET_FILE"
  awk -v type="$commit_type" 'NR == 2 { print "\"test-changelog-vite\": " type } { print }' "$CHANGESET_FILE" > "$CHANGESET_FILE.tmp" && mv "$CHANGESET_FILE.tmp" "$CHANGESET_FILE"  awk 'NR == 3 { print "---\n" } { print }' "$CHANGESET_FILE" > "$CHANGESET_FILE.tmp" && mv "$CHANGESET_FILE.tmp" "$CHANGESET_FILE"
  awk -v msg="$commit_description" 'NR == 5 { print msg } { print }' "$CHANGESET_FILE" > "$CHANGESET_FILE.tmp" && mv "$CHANGESET_FILE.tmp" "$CHANGESET_FILE"

  git pull

  # Добавляем изменённый changeset-файл в коммит
  git add .

  git commit -m "changelog update" --no-verify

  # Получаем имя текущей ветки
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

  # Выполняем git push
  if [ -n "$CURRENT_BRANCH" ]; then
    echo "📤 Выполняем git push origin $CURRENT_BRANCH"
    git push origin "$CURRENT_BRANCH" --no-verify
    echo "Success"
  else
    echo "❌ Не удалось определить текущую ветку для git push"
    exit 1
  fi
else
  echo "ℹ️ Ветка $CURRENT_BRANCH не соответствует pattern 'feature/*' — changeset не обрабатывается"
fi