name: Changeset Bot
on:
  push:
    branches: ["main"]
jobs:
  apply-changesets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: release new versions"
          createGithubReleases: true
