name: Changeset Bot
on:
  push:
    branches: ["main"]
jobs:
  apply-changesets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: changesets/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
